name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.8
      - name: Run Ruff
        run: ruff check --output-format=github .
      - name: Check imports
        run: ruff check --select I --output-format=github .
      - name: Check formatting
        run: ruff format --check .
